# Generated by Django 5.2.15 on 2026-07-06 16:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ant_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('20000.00'), help_text='Un gasto por debajo de este monto se considera hormiga (salvo los fijos).', max_digits=14, verbose_name='umbral hormiga'),
        ),
    ]
