# Generated by Django 5.2.15 on 2026-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_ant_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_big_expenses',
            field=models.BooleanField(default=True, help_text='Clasificar por monto: un gasto que llega al umbral cuenta como grande solo. Si se apaga, un gasto es grande únicamente cuando se marca a mano.', verbose_name='gastos grandes automáticos'),
        ),
    ]
