# Generated by Django 5.2.15 on 2026-08-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_auto_big_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_tour',
            field=models.BooleanField(default=False, help_text='Se marca cuando el usuario completa o salta el recorrido inicial.', verbose_name='vio el tour de bienvenida'),
        ),
    ]
