# Generated by Django 5.2.15 on 2026-07-01 00:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('fixed', 'Fijo'), ('variable', 'Variable'), ('ant', 'Hormiga')], max_length=10, verbose_name='tipo')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='ícono')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='color')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='transactions.category')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto')),
                ('kind', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso'), ('transfer', 'Transferencia')], max_length=10, verbose_name='tipo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('is_paid', models.BooleanField(default=True, verbose_name='pagado')),
                ('is_shared', models.BooleanField(default=False, verbose_name='compartido')),
                ('shared_ratio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Parte que te corresponde (ej. 0.500 para mitad).', max_digits=4, verbose_name='proporción propia')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Importación'), ('api', 'API')], default='manual', max_length=10, verbose_name='origen')),
                ('external_id', models.CharField(blank=True, help_text='Para deduplicar importaciones.', max_length=120, null=True, verbose_name='id externo')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_category_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'period'], name='transaction_owner_i_d5eab5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'kind', 'period'], name='transaction_owner_i_9d5673_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('wallet', 'external_id'), name='unique_external_id_per_wallet'),
        ),
    ]
