# Generated by Django 5.2.15 on 2026-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_recurring_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installments_current',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cuota'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installments_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cuotas totales'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='para revisar'),
        ),
    ]
