# Generated by Django 5.2.15 on 2026-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_installments_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_big',
            field=models.BooleanField(default=False, verbose_name='gasto grande'),
        ),
    ]
