# Generated by Django 5.2.15 on 2026-07-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importbatch_confirmed'),
        ('transactions', '0004_transaction_is_big'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='imports.importbatch'),
        ),
    ]
