# Generated by Django 5.2.15 on 2026-08-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_import_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
