# Generated by Django 5.2.15 on 2026-07-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='símbolo')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('fiat_cash', 'Dólar billete'), ('stablecoin', 'Stablecoin (USDT/USDC)'), ('crypto', 'Cripto'), ('stock_cedear', 'Acción / CEDEAR')], max_length=20, verbose_name='tipo')),
                ('quote_currency', models.CharField(default='USD', max_length=4, verbose_name='moneda de cotización')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80, verbose_name='ubicación')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='cantidad')),
                ('avg_buy_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='precio promedio de compra')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='savings.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenencia',
                'verbose_name_plural': 'tenencias',
                'ordering': ['asset__symbol', 'location'],
            },
        ),
        migrations.CreateModel(
            name='SavingsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('kind', models.CharField(choices=[('deposit', 'Aporte'), ('withdraw', 'Rescate'), ('buy', 'Compra'), ('sell', 'Venta'), ('convert', 'Conversión')], max_length=10, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='cantidad')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='precio de la operación')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='período')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='savings.asset')),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_movements', to='wallets.wallet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de ahorro',
                'verbose_name_plural': 'movimientos de ahorro',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ars', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='precio en ARS')),
                ('source', models.CharField(choices=[('api', 'API'), ('manual', 'Manual')], default='manual', max_length=10, verbose_name='fuente')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='tomado el')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='savings.asset')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['asset', '-fetched_at'], name='savings_pri_asset_i_6b9f5a_idx')],
            },
        ),
    ]
