# Generated by Django 5.2.15 on 2026-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsmovement',
            name='ars_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='monto en pesos'),
        ),
        migrations.AddField(
            model_name='savingsmovement',
            name='location',
            field=models.CharField(blank=True, max_length=80, verbose_name='ubicación'),
        ),
    ]
