# Generated by Django 5.2.15 on 2026-07-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsmovement_ars_amount_savingsmovement_location'),
        ('transactions', '0003_transaction_installments_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsmovement',
            name='linked_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_movement', to='transactions.transaction'),
        ),
    ]
