# Generated by Django 5.2.15 on 2026-07-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('bank', 'Banco'), ('wallet', 'Billetera virtual'), ('cash', 'Efectivo'), ('credit_card', 'Tarjeta de crédito')], max_length=20, verbose_name='tipo')),
                ('currency', models.CharField(default='ARS', max_length=3, verbose_name='moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('closing_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de cierre')),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'billetera',
                'verbose_name_plural': 'billeteras',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_wallet_name_per_owner')],
            },
        ),
    ]
