# Generated by Django 5.2.15 on 2026-07-03 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='período')),
                ('is_paid', models.BooleanField(default=False, verbose_name='pagado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_statements', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'resumen de tarjeta',
                'verbose_name_plural': 'resúmenes de tarjeta',
                'constraints': [models.UniqueConstraint(fields=('wallet', 'period'), name='unique_statement_per_wallet_period')],
            },
        ),
    ]
