# Generated by Django 5.2.15 on 2026-07-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto por defecto')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, verbose_name='día del mes')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='transactions.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'gasto fijo recurrente',
                'verbose_name_plural': 'gastos fijos recurrentes',
                'ordering': ['day_of_month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='período')),
                ('expected_income', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='sueldo esperado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presupuesto mensual',
                'verbose_name_plural': 'presupuestos mensuales',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'period'), name='unique_budget_per_owner_period')],
            },
        ),
    ]
