# Generated by Django 5.2.15 on 2026-08-06 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='período')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto esperado')),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='monto cobrado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fuente de ingreso',
                'verbose_name_plural': 'fuentes de ingreso',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['owner', 'period'], name='budgets_inc_owner_i_610c29_idx')],
            },
        ),
    ]
