# Generated by Django 5.2.15 on 2026-08-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_incomesource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='received_amount',
        ),
    ]
