# Generated by Django 5.2.15 on 2026-07-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('uala', 'Ualá'), ('personalpay', 'Personal Pay'), ('bank_icbc', 'Banco ICBC'), ('bank_galicia', 'Banco Galicia'), ('generic_csv', 'CSV genérico')], max_length=20, verbose_name='fuente')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='archivo')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='importado el')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='filas totales')),
                ('rows_imported', models.PositiveIntegerField(default=0, verbose_name='filas importadas')),
                ('rows_skipped', models.PositiveIntegerField(default=0, verbose_name='filas omitidas (duplicadas)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'importación',
                'verbose_name_plural': 'importaciones',
                'ordering': ['-imported_at'],
            },
        ),
    ]
