# Generated by Django 5.2.15 on 2026-07-01 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/', verbose_name='archivo'),
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Se busca dentro de la descripción (sin distinguir mayúsculas).', max_length=80, verbose_name='palabra clave')),
                ('priority', models.IntegerField(default=100, help_text='Menor = se evalúa primero.', verbose_name='prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='transactions.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'regla de categorización',
                'verbose_name_plural': 'reglas de categorización',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
