# Generated by Django 5.2.15 on 2026-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_importbatch_file_categoryrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('uala', 'Ualá'), ('personalpay', 'Personal Pay'), ('bank_icbc', 'Banco ICBC'), ('bank_galicia', 'Banco Galicia'), ('card_icbc', 'Tarjeta ICBC'), ('generic_csv', 'CSV genérico')], max_length=20, verbose_name='fuente'),
        ),
    ]
