# Generated by Django 5.2.15 on 2026-07-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_importbatch_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='confirmada'),
        ),
    ]
